package mx.com.evotae.appxtreme.main.service.datasource

class XTServicesCarrier{
    companion object {
        val carriersMap = mutableMapOf<String, String>(
            "103" to "CFE",
            "104" to "GOBIERNODF CDMX",
            "182" to "GOOGLEPLAY",
            "180" to "NETFLIX",
            "179" to "FACTURA TELCEL",
            "178" to "CASINOS CALIENTE",
            "175" to "SPOTIFY",
            "13" to "TESTRECARGAFEE",
            "102" to "SKYVeTV",
            "101" to "TELMEX",
            "105" to "AXTEL",
            "106" to "Dish",
            "107" to "ATT",
            "109" to "MEGACABLE",
            "114" to "CABLEVISION/IZZI",
            "115" to "CABLEMAS",
            "118" to "TOTAL PLAY",
            "119" to "FACTURA MOVISTAR",
            "120" to "FACTURA NEXTEL",
            "121" to "INFONAVIT",
            "123" to "NATURGY GAS NATURAL",
            "137" to "GOBIERNO ESTADO DE MEXICO",
            "148" to "XBOX",
            "152" to "PLAYSTATION",
            "155" to "NINTENDO",
            "156" to "CINEPOLIS",
            "158" to "ARABELA",
            "159" to "AVON",
            "162" to "JAFRA",
            "163" to "L BEL",
            "164" to "NATURA",
            "168" to "TUPERWARE",
            "172" to "IAVE/PASEURBANO",
            "181" to "BLIM",
            "179" to "FACTURA TELCEL",
            "176" to "DEEZER",
            "167" to "SWISSJUST",
            "161" to "ILUSION",
            "154" to "BAJA LIBROS",
            "153" to "SONY PLUS",
            "146" to "CLUB PENGUIN",
            "147" to "CLUB AMERICA",
            "117" to "CABLEVISION SALTILLO",
            "116" to "CABLEVISION MONTERREY",
            "142" to "GOBIERNO TABASCO",
            "141" to "GOBIERNO CHIAPAS",
            "140" to "GOBIERNO QUERETARO",
            "139" to "GOBIERNO MICHOACAN",
            "138" to "GOBIERNO HIDALGO",
            "136" to "GOBIERNO CHIHUAHUA",
            "129" to "CMAPAS SALAMANCA",
            "128" to "SADM MONTERREY",
            "108" to "TELNOR",
            "111" to "START TV",
        )
    }
}
